/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, ValidateNested, IsOptional } from "class-validator";
import { OrganizationsWorkspaceCreateNestedManyWithoutWorkspacesInput } from "./OrganizationsWorkspaceCreateNestedManyWithoutWorkspacesInput";
import { Type } from "class-transformer";
import { QlikWorkspaceCreateNestedManyWithoutWorkspacesInput } from "./QlikWorkspaceCreateNestedManyWithoutWorkspacesInput";
import { UsersWorkspaceCreateNestedManyWithoutWorkspacesInput } from "./UsersWorkspaceCreateNestedManyWithoutWorkspacesInput";

@InputType()
class WorkspaceCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => OrganizationsWorkspaceCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => OrganizationsWorkspaceCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => OrganizationsWorkspaceCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  organizationsWorkspaces?: OrganizationsWorkspaceCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: false,
    type: () => QlikWorkspaceCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => QlikWorkspaceCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => QlikWorkspaceCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  qlikWorkspaces?: QlikWorkspaceCreateNestedManyWithoutWorkspacesInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  slug!: string;

  @ApiProperty({
    required: false,
    type: () => UsersWorkspaceCreateNestedManyWithoutWorkspacesInput,
  })
  @ValidateNested()
  @Type(() => UsersWorkspaceCreateNestedManyWithoutWorkspacesInput)
  @IsOptional()
  @Field(() => UsersWorkspaceCreateNestedManyWithoutWorkspacesInput, {
    nullable: true,
  })
  usersWorkspaces?: UsersWorkspaceCreateNestedManyWithoutWorkspacesInput;
}

export { WorkspaceCreateInput as WorkspaceCreateInput };
