/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Workspace as PrismaWorkspace } from "@prisma/client";

export class WorkspaceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.WorkspaceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.workspace.count(args);
  }

  async workspaces<T extends Prisma.WorkspaceFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.WorkspaceFindManyArgs>
  ): Promise<PrismaWorkspace[]> {
    return this.prisma.workspace.findMany<Prisma.WorkspaceFindManyArgs>(args);
  }
  async workspace<T extends Prisma.WorkspaceFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WorkspaceFindUniqueArgs>
  ): Promise<PrismaWorkspace | null> {
    return this.prisma.workspace.findUnique(args);
  }
  async createWorkspace<T extends Prisma.WorkspaceCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WorkspaceCreateArgs>
  ): Promise<PrismaWorkspace> {
    return this.prisma.workspace.create<T>(args);
  }
  async updateWorkspace<T extends Prisma.WorkspaceUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WorkspaceUpdateArgs>
  ): Promise<PrismaWorkspace> {
    return this.prisma.workspace.update<T>(args);
  }
  async deleteWorkspace<T extends Prisma.WorkspaceDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.WorkspaceDeleteArgs>
  ): Promise<PrismaWorkspace> {
    return this.prisma.workspace.delete(args);
  }
}
