/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserVerificationCodeService } from "../userVerificationCode.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserVerificationCodeCreateInput } from "./UserVerificationCodeCreateInput";
import { UserVerificationCode } from "./UserVerificationCode";
import { UserVerificationCodeFindManyArgs } from "./UserVerificationCodeFindManyArgs";
import { UserVerificationCodeWhereUniqueInput } from "./UserVerificationCodeWhereUniqueInput";
import { UserVerificationCodeUpdateInput } from "./UserVerificationCodeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserVerificationCodeControllerBase {
  constructor(
    protected readonly service: UserVerificationCodeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserVerificationCode })
  @nestAccessControl.UseRoles({
    resource: "UserVerificationCode",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserVerificationCode(
    @common.Body() data: UserVerificationCodeCreateInput
  ): Promise<UserVerificationCode> {
    return await this.service.createUserVerificationCode({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verificationCode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserVerificationCode] })
  @ApiNestedQuery(UserVerificationCodeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserVerificationCode",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userVerificationCodes(
    @common.Req() request: Request
  ): Promise<UserVerificationCode[]> {
    const args = plainToClass(UserVerificationCodeFindManyArgs, request.query);
    return this.service.userVerificationCodes({
      ...args,
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verificationCode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserVerificationCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserVerificationCode",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userVerificationCode(
    @common.Param() params: UserVerificationCodeWhereUniqueInput
  ): Promise<UserVerificationCode | null> {
    const result = await this.service.userVerificationCode({
      where: params,
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verificationCode: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserVerificationCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserVerificationCode",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserVerificationCode(
    @common.Param() params: UserVerificationCodeWhereUniqueInput,
    @common.Body() data: UserVerificationCodeUpdateInput
  ): Promise<UserVerificationCode | null> {
    try {
      return await this.service.updateUserVerificationCode({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          expiresAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          verificationCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserVerificationCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserVerificationCode",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserVerificationCode(
    @common.Param() params: UserVerificationCodeWhereUniqueInput
  ): Promise<UserVerificationCode | null> {
    try {
      return await this.service.deleteUserVerificationCode({
        where: params,
        select: {
          createdAt: true,
          expiresAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          verificationCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
