/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MfeService } from "../mfe.service";
import { MfeCreateInput } from "./MfeCreateInput";
import { Mfe } from "./Mfe";
import { MfeFindManyArgs } from "./MfeFindManyArgs";
import { MfeWhereUniqueInput } from "./MfeWhereUniqueInput";
import { MfeUpdateInput } from "./MfeUpdateInput";
import { UserMfeFindManyArgs } from "../../userMfe/base/UserMfeFindManyArgs";
import { UserMfe } from "../../userMfe/base/UserMfe";
import { UserMfeWhereUniqueInput } from "../../userMfe/base/UserMfeWhereUniqueInput";

export class MfeControllerBase {
  constructor(protected readonly service: MfeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mfe })
  async createMfe(@common.Body() data: MfeCreateInput): Promise<Mfe> {
    return await this.service.createMfe({
      data: {
        ...data,

        mfe: data.mfe
          ? {
              connect: data.mfe,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        active: true,
        authenticationRequired: true,
        createdAt: true,
        description: true,
        id: true,
        key: true,

        mfe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Mfe] })
  @ApiNestedQuery(MfeFindManyArgs)
  async mfes(@common.Req() request: Request): Promise<Mfe[]> {
    const args = plainToClass(MfeFindManyArgs, request.query);
    return this.service.mfes({
      ...args,
      select: {
        active: true,
        authenticationRequired: true,
        createdAt: true,
        description: true,
        id: true,
        key: true,

        mfe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mfe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mfe(@common.Param() params: MfeWhereUniqueInput): Promise<Mfe | null> {
    const result = await this.service.mfe({
      where: params,
      select: {
        active: true,
        authenticationRequired: true,
        createdAt: true,
        description: true,
        id: true,
        key: true,

        mfe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mfe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMfe(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() data: MfeUpdateInput
  ): Promise<Mfe | null> {
    try {
      return await this.service.updateMfe({
        where: params,
        data: {
          ...data,

          mfe: data.mfe
            ? {
                connect: data.mfe,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          active: true,
          authenticationRequired: true,
          createdAt: true,
          description: true,
          id: true,
          key: true,

          mfe: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mfe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMfe(
    @common.Param() params: MfeWhereUniqueInput
  ): Promise<Mfe | null> {
    try {
      return await this.service.deleteMfe({
        where: params,
        select: {
          active: true,
          authenticationRequired: true,
          createdAt: true,
          description: true,
          id: true,
          key: true,

          mfe: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/mfes")
  @ApiNestedQuery(MfeFindManyArgs)
  async findMfes(
    @common.Req() request: Request,
    @common.Param() params: MfeWhereUniqueInput
  ): Promise<Mfe[]> {
    const query = plainToClass(MfeFindManyArgs, request.query);
    const results = await this.service.findMfes(params.id, {
      ...query,
      select: {
        active: true,
        authenticationRequired: true,
        createdAt: true,
        description: true,
        id: true,
        key: true,

        mfe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/mfes")
  async connectMfes(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: MfeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mfes: {
        connect: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/mfes")
  async updateMfes(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: MfeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mfes: {
        set: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/mfes")
  async disconnectMfes(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: MfeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mfes: {
        disconnect: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/usersMfes")
  @ApiNestedQuery(UserMfeFindManyArgs)
  async findUsersMfes(
    @common.Req() request: Request,
    @common.Param() params: MfeWhereUniqueInput
  ): Promise<UserMfe[]> {
    const query = plainToClass(UserMfeFindManyArgs, request.query);
    const results = await this.service.findUsersMfes(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        mfeId: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/usersMfes")
  async connectUsersMfes(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: UserMfeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usersMfes: {
        connect: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/usersMfes")
  async updateUsersMfes(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: UserMfeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usersMfes: {
        set: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/usersMfes")
  async disconnectUsersMfes(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: UserMfeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      usersMfes: {
        disconnect: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }
}
