/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  IsString,
  ValidateNested,
} from "class-validator";
import { MfeWhereUniqueInput } from "./MfeWhereUniqueInput";
import { Type } from "class-transformer";
import { MfeUpdateManyWithoutMfesInput } from "./MfeUpdateManyWithoutMfesInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { UserMfeUpdateManyWithoutMfesInput } from "./UserMfeUpdateManyWithoutMfesInput";

@InputType()
class MfeUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  active?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  authenticationRequired?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  key?: string | null;

  @ApiProperty({
    required: false,
    type: () => MfeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MfeWhereUniqueInput)
  @IsOptional()
  @Field(() => MfeWhereUniqueInput, {
    nullable: true,
  })
  mfe?: MfeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => MfeUpdateManyWithoutMfesInput,
  })
  @ValidateNested()
  @Type(() => MfeUpdateManyWithoutMfesInput)
  @IsOptional()
  @Field(() => MfeUpdateManyWithoutMfesInput, {
    nullable: true,
  })
  mfes?: MfeUpdateManyWithoutMfesInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => UserMfeUpdateManyWithoutMfesInput,
  })
  @ValidateNested()
  @Type(() => UserMfeUpdateManyWithoutMfesInput)
  @IsOptional()
  @Field(() => UserMfeUpdateManyWithoutMfesInput, {
    nullable: true,
  })
  usersMfes?: UserMfeUpdateManyWithoutMfesInput;
}

export { MfeUpdateInput as MfeUpdateInput };
