/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { MfeWhereUniqueInput } from "./MfeWhereUniqueInput";
import { MfeListRelationFilter } from "./MfeListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { UserMfeListRelationFilter } from "../../userMfe/base/UserMfeListRelationFilter";

@InputType()
class MfeWhereInput {
  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  active?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  authenticationRequired?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  key?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => MfeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MfeWhereUniqueInput)
  @IsOptional()
  @Field(() => MfeWhereUniqueInput, {
    nullable: true,
  })
  mfe?: MfeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => MfeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MfeListRelationFilter)
  @IsOptional()
  @Field(() => MfeListRelationFilter, {
    nullable: true,
  })
  mfes?: MfeListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => UserMfeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserMfeListRelationFilter)
  @IsOptional()
  @Field(() => UserMfeListRelationFilter, {
    nullable: true,
  })
  usersMfes?: UserMfeListRelationFilter;
}

export { MfeWhereInput as MfeWhereInput };
