/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsBoolean,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserConfigCreateNestedManyWithoutUsersInput } from "./UserConfigCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { UsersWorkspaceCreateNestedManyWithoutUsersInput } from "./UsersWorkspaceCreateNestedManyWithoutUsersInput";
import { UserVerificationCodeCreateNestedManyWithoutUsersInput } from "./UserVerificationCodeCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  status?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => UserConfigCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserConfigCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserConfigCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userConfigs?: UserConfigCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: () => UsersWorkspaceCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UsersWorkspaceCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UsersWorkspaceCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  usersWorkspaces?: UsersWorkspaceCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => UserVerificationCodeCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => UserVerificationCodeCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => UserVerificationCodeCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  userVerificationCodes?: UserVerificationCodeCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
