/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MfeService } from "../mfe.service";
import { MfeCreateInput } from "./MfeCreateInput";
import { Mfe } from "./Mfe";
import { MfeFindManyArgs } from "./MfeFindManyArgs";
import { MfeWhereUniqueInput } from "./MfeWhereUniqueInput";
import { MfeUpdateInput } from "./MfeUpdateInput";
import { UserAFindManyArgs } from "../../userA/base/UserAFindManyArgs";
import { UserA } from "../../userA/base/UserA";
import { UserAWhereUniqueInput } from "../../userA/base/UserAWhereUniqueInput";

export class MfeControllerBase {
  constructor(protected readonly service: MfeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mfe })
  async createMfe(@common.Body() data: MfeCreateInput): Promise<Mfe> {
    return await this.service.createMfe({
      data: data,
      select: {
        active: true,
        authenticationRequired: true,
        createdAt: true,
        description: true,
        id: true,
        key: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Mfe] })
  @ApiNestedQuery(MfeFindManyArgs)
  async mfes(@common.Req() request: Request): Promise<Mfe[]> {
    const args = plainToClass(MfeFindManyArgs, request.query);
    return this.service.mfes({
      ...args,
      select: {
        active: true,
        authenticationRequired: true,
        createdAt: true,
        description: true,
        id: true,
        key: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mfe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async mfe(@common.Param() params: MfeWhereUniqueInput): Promise<Mfe | null> {
    const result = await this.service.mfe({
      where: params,
      select: {
        active: true,
        authenticationRequired: true,
        createdAt: true,
        description: true,
        id: true,
        key: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mfe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMfe(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() data: MfeUpdateInput
  ): Promise<Mfe | null> {
    try {
      return await this.service.updateMfe({
        where: params,
        data: data,
        select: {
          active: true,
          authenticationRequired: true,
          createdAt: true,
          description: true,
          id: true,
          key: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mfe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMfe(
    @common.Param() params: MfeWhereUniqueInput
  ): Promise<Mfe | null> {
    try {
      return await this.service.deleteMfe({
        where: params,
        select: {
          active: true,
          authenticationRequired: true,
          createdAt: true,
          description: true,
          id: true,
          key: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/mfe")
  @ApiNestedQuery(UserAFindManyArgs)
  async findMfe(
    @common.Req() request: Request,
    @common.Param() params: MfeWhereUniqueInput
  ): Promise<UserA[]> {
    const query = plainToClass(UserAFindManyArgs, request.query);
    const results = await this.service.findMfe(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/mfe")
  async connectMfe(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: UserAWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mfe: {
        connect: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/mfe")
  async updateMfe(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: UserAWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mfe: {
        set: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/mfe")
  async disconnectMfe(
    @common.Param() params: MfeWhereUniqueInput,
    @common.Body() body: UserAWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mfe: {
        disconnect: body,
      },
    };
    await this.service.updateMfe({
      where: params,
      data,
      select: { id: true },
    });
  }
}
