/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Users, // @ts-ignore
  Mfe,
} from "@prisma/client";

export class UsersServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.UsersCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersCountArgs>
  ): Promise<number> {
    return this.prisma.users.count(args);
  }

  async usersItems<T extends Prisma.UsersFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersFindManyArgs>
  ): Promise<Users[]> {
    return this.prisma.users.findMany(args);
  }
  async users<T extends Prisma.UsersFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersFindUniqueArgs>
  ): Promise<Users | null> {
    return this.prisma.users.findUnique(args);
  }
  async createUsers<T extends Prisma.UsersCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersCreateArgs>
  ): Promise<Users> {
    return this.prisma.users.create<T>(args);
  }
  async updateUsers<T extends Prisma.UsersUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersUpdateArgs>
  ): Promise<Users> {
    return this.prisma.users.update<T>(args);
  }
  async deleteUsers<T extends Prisma.UsersDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersDeleteArgs>
  ): Promise<Users> {
    return this.prisma.users.delete(args);
  }

  async findMfes(
    parentId: string,
    args: Prisma.MfeFindManyArgs
  ): Promise<Mfe[]> {
    return this.prisma.users
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .mfes(args);
  }
}
